# Generated by Django 4.2.3 on 2023-07-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0002_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="testimonials")),
                ("review", models.TextField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
