# Generated by Django 4.2.3 on 2023-07-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0003_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(upload_to="static/testimonials"),
        ),
    ]
