# Generated by Django 4.2.3 on 2023-07-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0005_testimonial_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ]
            ),
        ),
    ]
