# Generated by Django 4.2.3 on 2023-07-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0006_alter_testimonial_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.FloatField(
                choices=[
                    (1, "1 Star"),
                    (1.5, "1.5 Stars"),
                    (2, "2 Stars"),
                    (2.5, "2.5 Stars"),
                    (3, "3 Stars"),
                    (3.5, "3.5 Stars"),
                    (4, "4 Stars"),
                    (4.5, "4.5 Stars"),
                    (5, "5 Stars"),
                ]
            ),
        ),
    ]
